//package personal.nfl.abcpermission
//
//import android.content.pm.PackageManager
//import android.os.Build
//import android.util.Log
//import androidx.core.app.ActivityCompat
//import androidx.core.content.ContextCompat
//import org.aspectj.lang.JoinPoint
//import org.aspectj.lang.ProceedingJoinPoint
//import org.aspectj.lang.annotation.*
//import personal.nfl.permission.support.constant.ApplicationConstant
//import personal.nfl.permission.support.util.AbcPermission
//import personal.nfl.permission.support.util.SharePreferenceTool
//import java.util.*
//
////Auto generated by apt,do not modify!!
//@Aspect
//class AutoCreate14 {
//    private val permissions =
//        arrayOf("android.permission.READ_CONTACTS", "android.permission.READ_PHONE_STATE")
//    @Pointcut("call(* personal.nfl.abcpermission.MainActivity.readContacts(..))")
//    fun methodCall() {
//    }
//
//    @Pointcut("\"execution(* personal.nfl.abcpermission.MainActivity.readContacts(..))\"")
//    fun methodExe() {
//    }
//
//    @Before("methodCall()")
//    fun beforeCall(joinPoint: JoinPoint?) {
//        Log.i("NFL", "before GetPermissions exe")
//    }
//
//    @Around("methodExe()")
//    fun aroundExe(proceedingJoinPoint: ProceedingJoinPoint): String? {
//        Log.i("NFL", "in GetPermissions exe")
//        if (Build.VERSION.SDK_INT < 14) {
//            return try {
//                proceedingJoinPoint.proceed() as String
//            } catch (throwable: Throwable) {
//                AbcPermission.permissionListener.exeException(throwable)
//                null
//            }
//        }
//        val permissionList: MutableList<String> = ArrayList()
//        for (permission in permissions) {
//            if (ContextCompat.checkSelfPermission(
//                    ApplicationConstant.nowActivity,
//                    permission
//                ) != PackageManager.PERMISSION_GRANTED
//            ) {
//                permissionList.add(permission)
//            }
//        }
//        if (permissionList.size == 0) {
//            return try {
//                proceedingJoinPoint.proceed() as String
//            } catch (throwable: Throwable) {
//                AbcPermission.permissionListener.exeException(throwable)
//                null
//            }
//        } else {
//            val permissionListTemp = arrayOfNulls<String>(permissionList.size)
//            for (i in permissionList.indices) {
//                permissionListTemp[i] = permissionList[i]
//            }
//            for (i in permissionList.indices) {
//                if (ContextCompat.checkSelfPermission(
//                        ApplicationConstant.nowActivity,
//                        permissionList[i]
//                    ) != PackageManager.PERMISSION_GRANTED
//                ) {
//                    Log.i("NFL", "PERMISSION_DENY")
//                    if (ActivityCompat.shouldShowRequestPermissionRationale(
//                            ApplicationConstant.nowActivity,
//                            permissionList[i]
//                        )
//                    ) {
//                        Log.i("NFL", "shouldShowRequestPermissionRationale")
//                        ActivityCompat.requestPermissions(
//                            ApplicationConstant.nowActivity,
//                            permissionListTemp,
//                            0
//                        )
//                        break
//                    } else {
//                        if (SharePreferenceTool.readObject(permissionList[i]) != null) {
//                            Log.i("NFL", "SharePreferenceTool not null ")
//                            if (!ActivityCompat.shouldShowRequestPermissionRationale(
//                                    ApplicationConstant.nowActivity,
//                                    permissionList[i]
//                                )
//                            ) {
//                                Log.i("NFL", "!shouldShowRequestPermissionRationale not null ")
//                                AbcPermission.permissionListener.cannotRequestAgain(
//                                    ApplicationConstant.nowActivity,
//                                    permissionListTemp
//                                )
//                                break
//                            }
//                        } else {
//                            if (permissionList.size - 1 == i) {
//                                ActivityCompat.requestPermissions(
//                                    ApplicationConstant.nowActivity,
//                                    permissionListTemp,
//                                    0
//                                )
//                            }
//                            SharePreferenceTool.saveObject("rejected", permissionList[i])
//                        }
//                    }
//                }
//            }
//        }
//        return null
//    }
//
//    @After("methodCall()")
//    fun afterCall(joinPoint: JoinPoint?) {
//        Log.i("NFL", "after GetPermissions exe")
//    }
//}